---
title: "git_00"
author: "Diana Flores"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Twinkle,Twinkle Little Brat 

How I wonder what you're at!

Up above the world so fly,

Like a tea tray in the sky.

Twinkle,twinkle,little brat!

How i wonder what you're at!
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,

   Shining with all his might:
   
He did his very best to make
   The billows smooth and bright—
   
And this was odd, because it was

   The middle of the night.

The moon was shining sulkily,

   Because she thought the sun
   
Had got no business to be there

   After the day was done—
   
"It's very rude of him," she said,

   "To come and spoil the fun!"
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In the realm where words reside,

A tapestry of verses untied.

Let me weave a poem for your delight,

A canvas of emotions, painted in light.

Amidst the dawn's golden glow,

Whispers of nature start to flow.

The sun awakens with a gentle kiss,

Bathing the earth in morning bliss.

Through the meadows, vibrant and green,

A symphony of colors, a vivid scene.

The flowers sway, their petals dance,

As butterflies flutter in graceful trance.

In twilight's embrace, the stars appear,

Scattered gems in a celestial sphere.

Their shimmering light, a cosmic guide,

Reflecting dreams that forever abide.

Upon the ocean's vast expanse,

Where waves meet the shore in a tender dance,

The salty air, a soothing balm,

Serenading hearts with a tranquil calm.
